// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package ma.enset.subs;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string chatMessage = 1;</code>
     * @return The chatMessage.
     */
    java.lang.String getChatMessage();
    /**
     * <code>string chatMessage = 1;</code>
     * @return The bytes for chatMessage.
     */
    com.google.protobuf.ByteString
        getChatMessageBytes();

    /**
     * <code>int64 userId = 2;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>int64 chatId = 3;</code>
     * @return The chatId.
     */
    long getChatId();
  }
  /**
   * Protobuf type {@code ChatRequest}
   */
  public  static final class ChatRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatRequest)
      ChatRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatRequest.newBuilder() to construct.
    private ChatRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatRequest() {
      chatMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              chatMessage_ = s;
              break;
            }
            case 16: {

              userId_ = input.readInt64();
              break;
            }
            case 24: {

              chatId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.enset.subs.Chat.internal_static_ChatRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.enset.subs.Chat.internal_static_ChatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.enset.subs.Chat.ChatRequest.class, ma.enset.subs.Chat.ChatRequest.Builder.class);
    }

    public static final int CHATMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object chatMessage_;
    /**
     * <code>string chatMessage = 1;</code>
     * @return The chatMessage.
     */
    public java.lang.String getChatMessage() {
      java.lang.Object ref = chatMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string chatMessage = 1;</code>
     * @return The bytes for chatMessage.
     */
    public com.google.protobuf.ByteString
        getChatMessageBytes() {
      java.lang.Object ref = chatMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <code>int64 userId = 2;</code>
     * @return The userId.
     */
    public long getUserId() {
      return userId_;
    }

    public static final int CHATID_FIELD_NUMBER = 3;
    private long chatId_;
    /**
     * <code>int64 chatId = 3;</code>
     * @return The chatId.
     */
    public long getChatId() {
      return chatId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getChatMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chatMessage_);
      }
      if (userId_ != 0L) {
        output.writeInt64(2, userId_);
      }
      if (chatId_ != 0L) {
        output.writeInt64(3, chatId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getChatMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chatMessage_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      if (chatId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, chatId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ma.enset.subs.Chat.ChatRequest)) {
        return super.equals(obj);
      }
      ma.enset.subs.Chat.ChatRequest other = (ma.enset.subs.Chat.ChatRequest) obj;

      if (!getChatMessage()
          .equals(other.getChatMessage())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getChatId()
          != other.getChatId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHATMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getChatMessage().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + CHATID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChatId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ma.enset.subs.Chat.ChatRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.subs.Chat.ChatRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.subs.Chat.ChatRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.subs.Chat.ChatRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.subs.Chat.ChatRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.subs.Chat.ChatRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.subs.Chat.ChatRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.enset.subs.Chat.ChatRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.enset.subs.Chat.ChatRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ma.enset.subs.Chat.ChatRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.enset.subs.Chat.ChatRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.enset.subs.Chat.ChatRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ma.enset.subs.Chat.ChatRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatRequest)
        ma.enset.subs.Chat.ChatRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ma.enset.subs.Chat.internal_static_ChatRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ma.enset.subs.Chat.internal_static_ChatRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ma.enset.subs.Chat.ChatRequest.class, ma.enset.subs.Chat.ChatRequest.Builder.class);
      }

      // Construct using ma.enset.subs.Chat.ChatRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        chatMessage_ = "";

        userId_ = 0L;

        chatId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ma.enset.subs.Chat.internal_static_ChatRequest_descriptor;
      }

      @java.lang.Override
      public ma.enset.subs.Chat.ChatRequest getDefaultInstanceForType() {
        return ma.enset.subs.Chat.ChatRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ma.enset.subs.Chat.ChatRequest build() {
        ma.enset.subs.Chat.ChatRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ma.enset.subs.Chat.ChatRequest buildPartial() {
        ma.enset.subs.Chat.ChatRequest result = new ma.enset.subs.Chat.ChatRequest(this);
        result.chatMessage_ = chatMessage_;
        result.userId_ = userId_;
        result.chatId_ = chatId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ma.enset.subs.Chat.ChatRequest) {
          return mergeFrom((ma.enset.subs.Chat.ChatRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ma.enset.subs.Chat.ChatRequest other) {
        if (other == ma.enset.subs.Chat.ChatRequest.getDefaultInstance()) return this;
        if (!other.getChatMessage().isEmpty()) {
          chatMessage_ = other.chatMessage_;
          onChanged();
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getChatId() != 0L) {
          setChatId(other.getChatId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ma.enset.subs.Chat.ChatRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ma.enset.subs.Chat.ChatRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object chatMessage_ = "";
      /**
       * <code>string chatMessage = 1;</code>
       * @return The chatMessage.
       */
      public java.lang.String getChatMessage() {
        java.lang.Object ref = chatMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chatMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string chatMessage = 1;</code>
       * @return The bytes for chatMessage.
       */
      public com.google.protobuf.ByteString
          getChatMessageBytes() {
        java.lang.Object ref = chatMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chatMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string chatMessage = 1;</code>
       * @param value The chatMessage to set.
       * @return This builder for chaining.
       */
      public Builder setChatMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chatMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string chatMessage = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatMessage() {
        
        chatMessage_ = getDefaultInstance().getChatMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string chatMessage = 1;</code>
       * @param value The bytes for chatMessage to set.
       * @return This builder for chaining.
       */
      public Builder setChatMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        chatMessage_ = value;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 2;</code>
       * @return The userId.
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private long chatId_ ;
      /**
       * <code>int64 chatId = 3;</code>
       * @return The chatId.
       */
      public long getChatId() {
        return chatId_;
      }
      /**
       * <code>int64 chatId = 3;</code>
       * @param value The chatId to set.
       * @return This builder for chaining.
       */
      public Builder setChatId(long value) {
        
        chatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 chatId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatId() {
        
        chatId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatRequest)
    }

    // @@protoc_insertion_point(class_scope:ChatRequest)
    private static final ma.enset.subs.Chat.ChatRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ma.enset.subs.Chat.ChatRequest();
    }

    public static ma.enset.subs.Chat.ChatRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatRequest>
        PARSER = new com.google.protobuf.AbstractParser<ChatRequest>() {
      @java.lang.Override
      public ChatRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ma.enset.subs.Chat.ChatRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChatResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string chatMessage = 1;</code>
     * @return The chatMessage.
     */
    java.lang.String getChatMessage();
    /**
     * <code>string chatMessage = 1;</code>
     * @return The bytes for chatMessage.
     */
    com.google.protobuf.ByteString
        getChatMessageBytes();

    /**
     * <code>int64 userId = 2;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>int64 chatId = 3;</code>
     * @return The chatId.
     */
    long getChatId();
  }
  /**
   * Protobuf type {@code ChatResponse}
   */
  public  static final class ChatResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatResponse)
      ChatResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatResponse.newBuilder() to construct.
    private ChatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatResponse() {
      chatMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              chatMessage_ = s;
              break;
            }
            case 16: {

              userId_ = input.readInt64();
              break;
            }
            case 24: {

              chatId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.enset.subs.Chat.internal_static_ChatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.enset.subs.Chat.internal_static_ChatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.enset.subs.Chat.ChatResponse.class, ma.enset.subs.Chat.ChatResponse.Builder.class);
    }

    public static final int CHATMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object chatMessage_;
    /**
     * <code>string chatMessage = 1;</code>
     * @return The chatMessage.
     */
    public java.lang.String getChatMessage() {
      java.lang.Object ref = chatMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string chatMessage = 1;</code>
     * @return The bytes for chatMessage.
     */
    public com.google.protobuf.ByteString
        getChatMessageBytes() {
      java.lang.Object ref = chatMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <code>int64 userId = 2;</code>
     * @return The userId.
     */
    public long getUserId() {
      return userId_;
    }

    public static final int CHATID_FIELD_NUMBER = 3;
    private long chatId_;
    /**
     * <code>int64 chatId = 3;</code>
     * @return The chatId.
     */
    public long getChatId() {
      return chatId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getChatMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chatMessage_);
      }
      if (userId_ != 0L) {
        output.writeInt64(2, userId_);
      }
      if (chatId_ != 0L) {
        output.writeInt64(3, chatId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getChatMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chatMessage_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      if (chatId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, chatId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ma.enset.subs.Chat.ChatResponse)) {
        return super.equals(obj);
      }
      ma.enset.subs.Chat.ChatResponse other = (ma.enset.subs.Chat.ChatResponse) obj;

      if (!getChatMessage()
          .equals(other.getChatMessage())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getChatId()
          != other.getChatId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHATMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getChatMessage().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + CHATID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChatId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ma.enset.subs.Chat.ChatResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.subs.Chat.ChatResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.subs.Chat.ChatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.subs.Chat.ChatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.subs.Chat.ChatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.subs.Chat.ChatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.subs.Chat.ChatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.enset.subs.Chat.ChatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.enset.subs.Chat.ChatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ma.enset.subs.Chat.ChatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.enset.subs.Chat.ChatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.enset.subs.Chat.ChatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ma.enset.subs.Chat.ChatResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatResponse)
        ma.enset.subs.Chat.ChatResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ma.enset.subs.Chat.internal_static_ChatResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ma.enset.subs.Chat.internal_static_ChatResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ma.enset.subs.Chat.ChatResponse.class, ma.enset.subs.Chat.ChatResponse.Builder.class);
      }

      // Construct using ma.enset.subs.Chat.ChatResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        chatMessage_ = "";

        userId_ = 0L;

        chatId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ma.enset.subs.Chat.internal_static_ChatResponse_descriptor;
      }

      @java.lang.Override
      public ma.enset.subs.Chat.ChatResponse getDefaultInstanceForType() {
        return ma.enset.subs.Chat.ChatResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ma.enset.subs.Chat.ChatResponse build() {
        ma.enset.subs.Chat.ChatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ma.enset.subs.Chat.ChatResponse buildPartial() {
        ma.enset.subs.Chat.ChatResponse result = new ma.enset.subs.Chat.ChatResponse(this);
        result.chatMessage_ = chatMessage_;
        result.userId_ = userId_;
        result.chatId_ = chatId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ma.enset.subs.Chat.ChatResponse) {
          return mergeFrom((ma.enset.subs.Chat.ChatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ma.enset.subs.Chat.ChatResponse other) {
        if (other == ma.enset.subs.Chat.ChatResponse.getDefaultInstance()) return this;
        if (!other.getChatMessage().isEmpty()) {
          chatMessage_ = other.chatMessage_;
          onChanged();
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getChatId() != 0L) {
          setChatId(other.getChatId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ma.enset.subs.Chat.ChatResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ma.enset.subs.Chat.ChatResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object chatMessage_ = "";
      /**
       * <code>string chatMessage = 1;</code>
       * @return The chatMessage.
       */
      public java.lang.String getChatMessage() {
        java.lang.Object ref = chatMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chatMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string chatMessage = 1;</code>
       * @return The bytes for chatMessage.
       */
      public com.google.protobuf.ByteString
          getChatMessageBytes() {
        java.lang.Object ref = chatMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chatMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string chatMessage = 1;</code>
       * @param value The chatMessage to set.
       * @return This builder for chaining.
       */
      public Builder setChatMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chatMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string chatMessage = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatMessage() {
        
        chatMessage_ = getDefaultInstance().getChatMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string chatMessage = 1;</code>
       * @param value The bytes for chatMessage to set.
       * @return This builder for chaining.
       */
      public Builder setChatMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        chatMessage_ = value;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 2;</code>
       * @return The userId.
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private long chatId_ ;
      /**
       * <code>int64 chatId = 3;</code>
       * @return The chatId.
       */
      public long getChatId() {
        return chatId_;
      }
      /**
       * <code>int64 chatId = 3;</code>
       * @param value The chatId to set.
       * @return This builder for chaining.
       */
      public Builder setChatId(long value) {
        
        chatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 chatId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatId() {
        
        chatId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatResponse)
    }

    // @@protoc_insertion_point(class_scope:ChatResponse)
    private static final ma.enset.subs.Chat.ChatResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ma.enset.subs.Chat.ChatResponse();
    }

    public static ma.enset.subs.Chat.ChatResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatResponse>
        PARSER = new com.google.protobuf.AbstractParser<ChatResponse>() {
      @java.lang.Override
      public ChatResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ma.enset.subs.Chat.ChatResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nChat.proto\"B\n\013ChatRequest\022\023\n\013chatMessa" +
      "ge\030\001 \001(\t\022\016\n\006userId\030\002 \001(\003\022\016\n\006chatId\030\003 \001(\003" +
      "\"C\n\014ChatResponse\022\023\n\013chatMessage\030\001 \001(\t\022\016\n" +
      "\006userId\030\002 \001(\003\022\016\n\006chatId\030\003 \001(\00326\n\013chatSer" +
      "vice\022\'\n\004chat\022\014.ChatRequest\032\r.ChatRespons" +
      "e(\0010\001B\017\n\rma.enset.subsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatRequest_descriptor,
        new java.lang.String[] { "ChatMessage", "UserId", "ChatId", });
    internal_static_ChatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ChatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatResponse_descriptor,
        new java.lang.String[] { "ChatMessage", "UserId", "ChatId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
